Repository ajour/ajour, pull requests merged in 2020-10, with the labels that each got.

#192 feat: abstracted all categories option for a cleaner interface
  src/gui/mod.rs
  src/gui/update.rs
Labels: type: enhancement

#181 feat: catalog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/core/src/addon.rs
  crates/core/src/catalog.rs
  crates/core/src/config/mod.rs
  crates/core/src/config/wow.rs
  crates/core/src/curse_api.rs
  crates/core/src/lib.rs
  crates/core/src/network.rs
  crates/core/src/tukui_api.rs
  src/gui/element.rs
  src/gui/mod.rs
  src/gui/style.rs
  src/gui/update.rs
Labels: type: feature

#213 add cli feature to update all addons
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  src/cli.rs
  src/main.rs
  src/update.rs
Labels: status: in progress, type: feature, type: tooling

#206 chore: add forest-night theme
  .gitignore
  README.md
  crates/core/src/theme/mod.rs
  src/gui/mod.rs
Labels: type: tooling

#257 feat: ptr and beta support
  CHANGELOG.md
  crates/core/src/addon.rs
  crates/core/src/config/mod.rs
  crates/core/src/config/wow.rs
  crates/core/src/curse_api.rs
  crates/core/src/tukui_api.rs
  src/gui/element.rs
  src/gui/mod.rs
  src/gui/update.rs
Labels: status: in progress, type: feature

#170 Chocolatey package documentation.
  INSTALL.md
Labels: status: upstream, type: documentation
