Repository ajour/ajour, pull requests merged in 2020-09, with the labels that each got.

#108 feat: able to easily select flavor from menu
  CHANGELOG.md
  src/addon.rs
  src/config/addons.rs
  src/config/mod.rs
  src/config/wow.rs
  src/fs/save.rs
  src/gui/element.rs
  src/gui/mod.rs
  src/gui/style.rs
  src/gui/update.rs
  src/parse.rs
Labels: status: in progress, type: feature

#111 feat: improve clarity of row titles to reflect current sort state
  CHANGELOG.md
  src/gui/element.rs
  src/gui/style.rs
  src/gui/update.rs
Labels: type: enhancement

#110 add local logging for debugging
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/config/mod.rs
  src/curse_api.rs
  src/error.rs
  src/fs/mod.rs
  src/fs/theme.rs
  src/gui/update.rs
  src/main.rs
  src/network.rs
  src/parse.rs
  src/theme/mod.rs
  src/utility.rs
Labels: status: in progress, type: enhancement

#119 header widget
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/widgets/Cargo.toml
  crates/widgets/src/lib.rs
  crates/widgets/src/renderer.rs
  crates/widgets/src/renderer/header.rs
  crates/widgets/src/widget.rs
  crates/widgets/src/widget/header.rs
  crates/widgets/src/widget/header/state.rs
  src/config/mod.rs
  src/gui/element.rs
  src/gui/mod.rs
  src/gui/update.rs
Labels: status: needs discussion
